spring.application.name=budget
server.port=9000
server.servlet.context-path=/budget

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tgojhvxmfoxwskrbmazy
spring.datasource.password=0neb@tchTwobatch

app.jwt.access.secret=zCZp4kS5P8aP0PpPrOZpJiyr6V7qvH7aT4i5s1K7Kk0=
app.jwt.refresh.secret=G6pQ3dR9Vv5zYkT2Z8yN5xF8dQ3gX7jK1eO4mF9wRkU=
app.jwt.access.expMs=1800000
app.jwt.refresh.expMs=7200000