spring.application.name=budget
server.port=9000
server.servlet.context-path=/budget

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tgojhvxmfoxwskrbmazy
spring.datasource.password=0neb@tchTwobatch